replicaCount: 1

fullnameOverride: "notif"

image: "notif:0.2.14"

service:
  type: NodePort
  port: 9000

postgresql:
  enabled: true
  postgresqlUsername: notifuser
  postgresqlPassword: notifpasswd
  postgresqlDatabase: notifdb
  persistence:
    size: 0.1Gi
  service:
    port: "5432"

jaeger:
  agentHost: "jaeger-agent.proj.svc.cluster.local"
  reporterLogSpans: "true"
  samplerType: "const"
  samplerParam: "1"

